/* Auto generated by configure, do not modify! */
#pragma once

#define BRANCH "InspIRCd-2.2"
#define VERSION "InspIRCd-2.2.0+pre"
#define REVISION "v2.0.15-507-g7bcb703"
#define SYSTEM "FreeBSD VPS-3023 9.2-RELEASE-p3"
#define INSPIRCD_SOCKETENGINE_NAME "kqueue"

#define CONFIG_PATH "/usr/home/j4jackj/inspircd/run/conf"
#define DATA_PATH "/usr/home/j4jackj/inspircd/run/data"
#define LOG_PATH "/usr/home/j4jackj/inspircd/run/logs"
#define MOD_PATH "/usr/home/j4jackj/inspircd/run/modules"

#define HAS_CLOCK_GETTIME

#include "threadengines/threadengine_pthread.h"
